### ISSUE TITLE
Dynamic lighting and Ambient lighting

### ISSUE THREAD

**Issue by uziyyds** [MaximovInk/AdvancedTilemap#1]
where is the code about Dynamic lighting and Ambient lighting， and how to use them？  can we use these two lighting at the same time？ looking forward your answerring， thank you！

**Comment by MaximovInk** [comment]
I removed dynamic lighting, because Unity implemented its own version, the latest commit is where you can find the code: [ed7f699 ](https://github.com/MaximovInk/AdvancedTilemap/tree/ed7f69937b5f7762496fcb1bdf13b9ffa63d38b5)  If you want, I can make a new version of this lighting. Sorry for the late reply

**Comment by MaximovInk** [comment]
added preview version of new lighting [71fc1ee ](https://github.com/MaximovInk/AdvancedTilemap/commit/71fc1ee0563ae48fb9053150d9b5cfcb91c4648a)
